name: Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.ref_name}}
          submodules: true
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache core files
        uses: actions/cache@v3
        id: cache-core
        with:
          path: |
            core/*
            !core/live2d.d.ts
          key: ${{ runner.os }}-core-${{ hashFiles('scripts/setup.js') }}

      - run: npm ci

      - if: steps.cache-core.outputs.cache-hit != 'true'
        run: npm run setup

      - uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test:ci
          
      - name: Commit files
        run: |
          git config --global user.name 'RaSan147'
          git config --global user.email '34002411+RaSan147@users.noreply.github.com'
          git add --all
          git commit -am "Automated report"
          git push


      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ github.workspace }}/dist
